### ISSUE TITLE
REGALS breaks with scipy 1.12.0

### ISSUE THREAD

**Issue by jbhopkins** [ando-lab/regals#12]
Hi folks,

I haven't done a lot of detective work to figure what's going wrong, but I'm getting an error using REGALS with scipy 1.12.0. Here's the error (with some RAW specific stuff omitted):

```
File "C:\bioxtasraw\bioxtasraw\SASCalc.py", line 4574, in create_regals_mixture
    prof_lambda_est = mixture.estimate_profile_lambda(sigma)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\bioxtasraw\bioxtasraw\REGALS.py", line 218, in estimate_profile_lambda
    AA = self.profile_problem(np.zeros((self.Nq,self.Nx)),err,False).todense()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\bioxtasraw\bioxtasraw\REGALS.py", line 262, in profile_problem
    AA = sp.vstack((sp.hstack(tuple(AAi)) for AAi in AA))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\biocat\miniconda3\envs\raw_build\Lib\site-packages\scipy\sparse\_construct.py", line 781, in vstack
    return _block([[b] for b in blocks], format, dtype, return_spmatrix=True)
                  ^^^^^^^^^^^^^^^^^^^^^

TypeError: iteration over a 0-d array
```

The scipy 1.12.0 changelog does have some notes about sparse.hstack and sparse.vstack:
https://docs.scipy.org/doc/scipy/release/1.12.0-notes.html

And the documentation has changed a bit to include a return type, but the example is the same, so I'm not sure what to make of that (it seems like it was always returning an array?):
1.11.4:
https://docs.scipy.org/doc/scipy-1.11.4/reference/generated/scipy.sparse.vstack.html#scipy.sparse.vstack
https://docs.scipy.org/doc/scipy-1.11.4/reference/generated/scipy.sparse.hstack.html#scipy.sparse.hstack

1.12.0:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.vstack.html
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.hstack.html

I'm happy to help as I can, but I'm hoping you might immediately recognize what the issue is and know how to fix it.

Jesse

**Comment by dxu16** [comment]
Hi Jesse, thanks for bringing this to our attention! It appears that the issue results from the output of the list comprehension with hstack being a generator while vstack expects a tuple. Once I explicitly convert the result to a tuple, the code seems to run without issue for me. I have added the change to the master branch, could you verify that it also works for you?

Thanks,
Darren

**Comment by jbhopkins** [comment]
Hi Darren,

That seems to fix it. Thanks for figuring it out and fixing it so quickly!

Jesse
