### ISSUE TITLE
Error using simple concentration in NrdE notebook

### ISSUE THREAD

**Issue by jbhopkins** [ando-lab/regals#6]
If I change the Bg1 concentration_class to simple in the NrdE notebook and remove the is zero conditions, when I run it it fails with the following output:

 1, x2 = 2.296672, delta_profile = [389.705 455.882 290.414  71.728]
 2, x2 = nan, delta_profile = [nan nan nan nan]
 3, x2 = nan, delta_profile = [nan nan nan nan]
/Users/jesse/miniconda2/envs/py3/lib/python3.7/site-packages/scipy/sparse/linalg/dsolve/linsolve.py:198: MatrixRankWarning: Matrix is exactly singular
  warn("Matrix is exactly singular", MatrixRankWarning)
 4, x2 = nan, delta_profile = [nan nan nan nan]

**Comment by jbhopkins** [comment]
This appears to be a problem with setting the lambdas. If I don't set those, it runs fine.

**Comment by spmeisburger** [comment]
I think I found the problem. The issues is `estimateConcentrationLambda()` returns `Inf` if you use a "simple" parameterization. You can turn off estimation and force lambda = 0 for that component by changing `ng` from 8 to `Inf`, as follows: (matlab)

`M.concentrationLambda = M.estimateConcentrationLambda(sigma,[Inf,Inf,Inf,8]);`

REGALS should check that all lambda values are valid -- I'll add an error message.
